# Buscando peliculas similares

*Comenzaremos cargando el conjunto de datos de MovieLens. Usando pandas, podemos cargar muy rápidamente las filas de los archivos u.data y you.item que nos interesan, y fusionarlos para que podamos trabajar con nombres de películas en lugar de ID. (En un trabajo de producción real, te quedarías con las identificaciones y te preocuparías por los nombres en la capa de visualización para hacer las cosas más eficientes. Pero esto nos permite entender lo que está pasando mejor por ahora)*

In [50]:
import pandas as pd
import numpy as np
from ast import literal_eval
import re

rating=pd.read_csv(r'./ratings_small.csv')
movie=pd.read_csv(r'./movies_metadata.csv')

regex = re.compile(r'[^0-9]') # Eliminamos todo lo que no sean números
movie['id']=movie['id'].replace(regex, '').astype(int)
ratingok=rating.merge(movie,left_on='movieId',right_on='id')
ratingok=ratingok[['movieId','belongs_to_collection']]
ratingok=ratingok.dropna()

ratingok.belongs_to_collection = ratingok.belongs_to_collection.fillna('{}')
ratingok.belongs_to_collection = ratingok.belongs_to_collection.apply(literal_eval)

ratingok = ratingok.join(pd.json_normalize(ratingok.pop('belongs_to_collection')))
ratingok=ratingok.dropna()
ratingok = ratingok[~ratingok.astype(str).duplicated()]
ratingok = ratingok[['movieId','id','name']]

ratingok=pd.merge(ratingok, rating, how = 'left', on = None, left_on = ['movieId'],   # match entre df para crear otro df
                 right_on = ['movieId'], left_index = False, right_index = False)
ratingok = ratingok[~ratingok.astype(str).duplicated()]
ratingok

C:\Users\Dell Inspiron\AppData\Local\Temp\ipykernel_10280\2499685230.py:7: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movie=pd.read_csv(r'./movies_metadata.csv')

       movieId      id                      name  userId  rating   timestamp
0         1371  1575.0          Rocky Collection       1     2.5  1260759135
1         1371  1575.0          Rocky Collection       4     4.0   949810302
2         1371  1575.0          Rocky Collection       7     3.0   851869160
3         1371  1575.0          Rocky Collection      19     4.0   855193404
4         1371  1575.0          Rocky Collection      21     3.0   853852263
...        ...     ...                       ...     ...     ...         ...
11778      440   230.0  The Godfather Collection     649     4.0   834424947
11779      440   230.0  The Godfather Collection     653     4.0   948161152
11780      440   230.0  The Godfather Collection     654     4.0  1145391964
11781      440   230.0  The Godfather Collection     662     3.0   839022409
11782      440   230.0  The Godfather Collection     667     3.0   847271534

[11783 rows x 6 columns]

**Ahora la increíble función pivot_table en un marco de datos construirá una matriz de clasificación de usuario / película. Observe cómo NAN indicó datos faltantes: películas que el usuario específico no calificó**

In [51]:
movieRating=ratingok.pivot_table(index='userId',columns=['name'],values='rating')
movieRating.head()

name,48 Hrs. Collection,A Nightmare on Elm Street Collection,AVP Collection,Aces Go Places Collection,Addams Family Collection,American Graffiti Collection,American Pie Collection,Back to the Future Collection,Batman Collection,Begotten Collection,...,The Party Collection,The Space Odyssey Series,The Terminator Collection,The Vampire Chronicles,The Vengeance Collection,The Whole Nine/Ten Yards Collection,Three Colors Collection,Torrente Collection,Transformers Collection,Wallace & Gromit Collection
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.5,3.5,3.0,NaN,3.0,NaN,3.0,4.5,3.0,NaN,...,NaN,NaN,3.0,5.0,NaN,NaN,3.0,3.0,3.0,NaN
3,4.0,NaN,2.5,4.0,3.0,NaN,NaN,NaN,NaN,3.0,...,NaN,3.5,NaN,NaN,NaN,NaN,NaN,2.5,2.5,NaN
4,NaN,NaN,5.0,NaN,5.0,4.0,4.0,5.0,NaN,NaN,...,5.0,4.0,NaN,NaN,3.0,3.0,NaN,NaN,NaN,3.0
5,NaN,NaN,4.0,NaN,3.5,4.0,NaN,4.0,NaN,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,NaN

**Vamos a extraer series de usuarios que calificaron American Pie Collection**

In [52]:
ameriP=movieRating['American Pie Collection']
ameriP.head()
#movieRating.info()

userId
1    4.0
2    3.0
3    NaN
4    4.0
5    NaN
Name: American Pie Collection, dtype: float64

**¡La función Pandas corrwith hace que sea realmente fácil calcular el vector de correlación por pares 'American Pie Collection' de la calificación del usuario con cualquier otra película! Después de eso, eliminaremos cualquier resultado que no tenga datos y construiremos un nuevo marco de datos de películas y su puntaje de correlación (similitud) con 'American Pie Collection'**

In [53]:
peliSimilar=movieRating.corrwith(ameriP)
peliSimilar=peliSimilar.dropna()
df=pd.DataFrame(peliSimilar)
df.head(15)

                                             0
name
48 Hrs. Collection                    0.286277
A Nightmare on Elm Street Collection  0.074208
AVP Collection                        0.252992
Aces Go Places Collection            -0.255274
Addams Family Collection             -0.021372
American Graffiti Collection          0.295767
American Pie Collection               1.000000
Back to the Future Collection         0.213082
Batman Collection                     0.277803
Begotten Collection                   0.284604
Cube Collection                       0.119991
Final Fantasy Collection              0.973004
Frankenstein (Universal Series)       0.021493
Ghost Rider Collection               -0.159739
Godzilla (Showa) Collection          -0.021372

**Ordenemos el resultado por puntuación de similitud, y deberíamos tener las películas más similares a 'American Pie Collection' Excepto... Nosotros no. ¡Estos resultados tienen sentido! Es por eso que es importante conocer sus datos: claramente nos perdimos algo importante**

In [54]:
peliSimilar.sort_values(ascending=False)

name
American Pie Collection                 1.000000
The Bible Collection                    0.973004
Rush Hour Collection                    0.973004
Final Fantasy Collection                0.973004
The Chronicles of Riddick Collection    0.973004
                                          ...
Ghost Rider Collection                 -0.159739
Speed Collection                       -0.159739
Aces Go Places Collection              -0.255274
Short Circuit Collection               -0.255274
Ringu Collection                       -0.255274
Length: 67, dtype: float64

**Nuestros resultados probablemente se están estropeando con películas que solo han sido vistas por un puñado de personas a las que también les gustó 'American Pie Collection'. Así que tenemos que deshacernos de las películas que sólo fueron vistas por unas pocas personas que están produciendo resultados espurios. Construyamos un nuevo marco de datos que cuente cuántas calificaciones existen para cada película y también la calificación promedio mientras estamos en ello, eso también podría ser útil más adelante.**

In [55]:
peliStats=ratingok.groupby('name').agg({'rating':[np.size,np.mean]})
peliStats.head()

                                     rating
                                       size      mean
name
48 Hrs. Collection                      315  3.874603
A Nightmare on Elm Street Collection    177  3.330508
AVP Collection                          380  3.677632
Aces Go Places Collection                44  3.625000
Addams Family Collection                215  3.674419

**Deje que Grid se deshaga de cualquier película calificada por menos de 100 personas y verifique las mejor calificadas que queden**

In [56]:
peliPopular=peliStats['rating']['size']>=100
peliStats[peliPopular].sort_values([('rating','mean')],ascending=False)[:15]

                                       rating
                                         size      mean
name
Planet of the Apes Original Collection    244  4.303279
Speed Collection                          244  4.303279
Ghost Rider Collection                    244  4.303279
Hard Target Collection                    244  4.303279
Psycho Collection                         324  4.256173
Silent Hill Collection                    324  4.256173
Monsters, Inc. Collection                 324  4.256173
The Endless Summer Collection             369  4.006775
The Chronicles of Riddick Collection      213  3.953052
The Bible Collection                      213  3.953052
Rush Hour Collection                      213  3.953052
The Chronicles of Narnia Collection       213  3.953052
Final Fantasy Collection                  213  3.953052
Ocean's Collection                        228  3.945175
48 Hrs. Collection                        315  3.874603

**100 aún puede ser demasiado bajo, pero estos resultados se ven bastante bien en cuanto a "películas bien calificadas de las que la gente ha oído hablar". Unamos estos datos con nuestro conjunto original de películas similares a 'American Pie Collection'**

In [62]:
df=peliStats[peliPopular].join(pd.DataFrame(peliSimilar, columns=['similarity']))
df.head()

C:\Users\Dell Inspiron\AppData\Local\Temp\ipykernel_10280\4014847833.py:1: FutureWarning: merging between different levels is deprecated and will be removed in a future version. (2 levels on the left, 1 on the right)
  df=peliStats[peliPopular].join(pd.DataFrame(peliSimilar, columns=['similarity']))

,"(rating, size)","(rating, mean)",similarity
name,,,
48 Hrs. Collection,315,3.874603,0.286277
A Nightmare on Elm Street Collection,177,3.330508,0.074208
AVP Collection,380,3.677632,0.252992
Addams Family Collection,215,3.674419,-0.021372
American Pie Collection,260,3.867308,1.000000

**y, ordenar estos nuevos resultados por puntaje similitar. Ese es un modo como este**

In [63]:
df.sort_values(['similarity'],ascending=False)[:15]

,"(rating, size)","(rating, mean)",similarity
name,,,
American Pie Collection,260,3.867308,1.000000
Rush Hour Collection,213,3.953052,0.973004
The Chronicles of Riddick Collection,213,3.953052,0.973004
The Bible Collection,213,3.953052,0.973004
The Chronicles of Narnia Collection,213,3.953052,0.973004
Final Fantasy Collection,213,3.953052,0.973004
The Space Odyssey Series,120,3.804167,0.734236
Kill Bill Collection,114,3.350877,0.507345
Ice Age Collection,114,3.350877,0.507345
Wallace & Gromit Collection,114,3.350877,0.507345
The Vengeance Collection,114,3.350877,0.507345
The Matrix Collection,114,3.350877,0.507345
The Butterfly Effect Collection,180,3.566667,0.401874
Torrente Collection,180,3.566667,0.401874
Transformers Collection,180,3.566667,0.401874